(() => {
'use strict';
const modes={
 salvage:{title:'파도 회수국',tag:'01 / BRING IT HOME',intro:'깊이 들어갈수록 수거는 빨라집니다. 조수가 덮치기 전 화물을 귀항시키세요.',goal:'자재 120개 정산',resource:'보관 자재',help:'해변·심해에서 자동 수거합니다. 심해는 수거가 2배지만 내구가 빠르게 줄어듭니다.\n귀항하면 화물이 자재로 정산되고 내구가 회복됩니다. 자재로 드론이나 선체를 강화하세요.\n120초 안에 누적 정산 120개. 내구 0 또는 시간 종료 시 실패.',actions:[['해변 수거','초당 화물 2 · 낮은 피해'],['심해 수거','초당 화물 4 · 높은 피해'],['귀항 정산','화물 보관 · 내구 회복']],upgrades:[['수거 드론','수거 +45% · 비용 18'],['선체 보강','피해 감소 · 비용 15']]},
 forge:{title:'태엽 공방',tag:'02 / ALLOCATION IS POWER',intro:'일꾼 3명을 채굴과 경비에 배분합니다. 주문을 납품하며 자동 공방을 키우세요.',goal:'주문 6건 납품',resource:'광석',help:'채굴 집중은 빠르지만 기지 피해가 큽니다. 경비 집중은 느리지만 내구를 회복합니다.\n광석 18개마다 납품 버튼으로 주문을 완성합니다. 채굴기 투자와 주문 납품 사이를 선택하세요.\n120초 안에 6건 납품. 내구 0 또는 시간 종료 시 실패.',actions:[['채굴 집중','생산 4/초 · 방어 0'],['균형 배분','생산 2.4/초 · 방어 1'],['경비 집중','생산 1/초 · 내구 회복']],upgrades:[['채굴기 증설','생산 +0.8/초 · 비용 16'],['주문 납품','광석 18 → 주문 1건']]},
 route:{title:'포자 운송소',tag:'03 / CHOOSE YOUR ROAD',intro:'안전길과 위험길을 골라 화물을 운송합니다. 운송 완료마다 다음 편을 준비하세요.',goal:'화물 5회 납품',resource:'운송 자재',help:'안전길은 14초, 위험길은 8초입니다. 위험길은 자재 15개를 주지만 도중에 내구를 잃습니다. 안전길 보상은 10개입니다.\n도착하면 다음 운송 버튼으로 새 편을 출발시킵니다. 호위를 강화하거나 자재를 써서 수리하세요.\n120초 안에 5회 납품. 내구 0 또는 시간 종료 시 실패.',actions:[['안전길','14초 · 자재 10 · 피해 없음'],['위험길','8초 · 자재 15 · 높은 피해'],['다음 운송','도착 후 새 편 출발']],upgrades:[['호위 강화','위험길 피해 감소 · 비용 12'],['긴급 수리','내구 +25 · 비용 8']]}
};
const q=new URLSearchParams(location.search),key=modes[q.get('game')]?q.get('game'):'salvage',m=modes[key],$=id=>document.getElementById(id);let s=null,muted=true,audio=null,last=performance.now(),frame=0;
document.title=m.title+' | 심다 PLAY';document.querySelectorAll('nav a').forEach(a=>{if(a.search.includes(key))a.classList.add('active')});['title','intro','goal'].forEach(id=>$(id).textContent=m[id]);$('eyebrow').textContent=m.tag;$('resourceLabel').textContent=m.resource;$('overlayTitle').textContent=m.title;$('help').textContent=m.help;
const buttons=[],upbuttons=[];
function create(container,label,desc,fn){const b=document.createElement('button');const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=label;small.textContent=desc;b.append(strong,small);b.onclick=fn;$(container).append(b);return b}
m.actions.forEach((v,i)=>buttons.push(create('actions',...v,()=>action(i))));m.upgrades.forEach((v,i)=>upbuttons.push(create('upgrades',...v,()=>upgrade(i))));
function tone(freq=450){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}catch{}}
function notice(t){$('notice').textContent=t;tone(540)}
function start(){$('overlay').querySelector('.eyebrow').textContent='작전 준비';s={status:'play',time:0,hp:100,res:0,cargo:0,delivered:0,level:0,armor:0,mode:0,trip:0,arrived:false,flash:0,events:0,low:false};last=performance.now();$('overlay').hidden=true;notice('작전 시작. '+m.goal);update();buttons[0].focus()}
function finish(win){$('overlay').querySelector('.eyebrow').textContent=win?'목표 달성':'다음 작전';s.status=win?'win':'lose';$('overlayTitle').textContent=win?'작전 완료':'작전 실패';$('help').textContent=win?m.goal+' 달성! 남은 시간 '+Math.ceil(120-s.time)+'초 · 내구 '+Math.ceil(s.hp)+'/100. 효율 점수 '+Math.round(Math.max(0,120-s.time)+s.hp)+'점. 다시 시작해서 다른 전략을 시험하세요.':(s.hp<=0?'내구가 소진됐습니다. 안전 선택이나 수리를 더 일찍 사용하세요.':'시간이 끝났습니다. 성장 투자와 목표 달성의 순서를 바꿔 보세요.');$('start').textContent='다시 시작';$('overlay').hidden=false;notice(win?'목표 달성':'작전 실패');$('start').focus();update()}
function action(i){if(!s||s.status!=='play')return;s.flash=.5;
 if(key==='salvage'){if(i===2){const amount=Math.floor(s.cargo);s.res+=amount;s.delivered+=amount;s.cargo=0;s.mode=2;notice('귀항: 자재 '+amount+'개 정산. 항구에서 내구 회복 중.');}else{s.mode=i;notice(i===0?'해변 수거 시작':'심해 수거 시작. 조수 피해 주의.');}}
 if(key==='forge'){s.mode=i;notice(m.actions[i][0]+'으로 배분 변경');}
 if(key==='route'){if(i===2){if(!s.arrived){notice('아직 운송 중입니다. 도착 후 출발하세요.');return;}s.arrived=false;s.trip=0;notice('새 운송 출발');}else{s.mode=i;notice(m.actions[i][0]+' 선택');}}
 check();update();}
function upgrade(i){if(!s||s.status!=='play')return;let cost;
 if(key==='salvage'){cost=i===0?18+6*s.level:15+5*s.armor;if(s.res<cost){notice('자재 '+cost+'개가 필요합니다.');return}s.res-=cost;if(i===0)s.level++;else{s.armor++;s.hp=Math.min(100,s.hp+10)}notice(m.upgrades[i][0]+' 완료');}
 if(key==='forge'){cost=i===0?16+6*s.level:18;if(s.res<cost){notice('광석 '+cost+'개가 필요합니다.');return}s.res-=cost;if(i===0){s.level++;notice('채굴기 증설 완료')}else{s.delivered++;s.hp=Math.min(100,s.hp+8);notice('주문 '+s.delivered+'/6 납품 · 내구 8 회복')}}
 if(key==='route'){if(i===1&&s.hp>=100){notice('내구가 가득 찼습니다. 자재를 사용하지 않았습니다.');return}cost=i===0?12+4*s.armor:8;if(s.res<cost){notice('운송 자재 '+cost+'개가 필요합니다.');return}s.res-=cost;if(i===0)s.armor++;else s.hp=Math.min(100,s.hp+25);notice(m.upgrades[i][0]+' 완료');}
 s.flash=.8;check();update();}
function check(){if(!s||s.status!=='play')return;const target=key==='salvage'?120:key==='forge'?6:5;if(s.hp<=0)finish(false);else if(s.delivered>=target)finish(true);else if(s.time>=120)finish(false);}
function tick(dt){if(!s||s.status!=='play')return;s.time+=dt;s.flash=Math.max(0,s.flash-dt);if(s.hp<30&&!s.low){s.low=true;notice('내구 30 미만! 안전 선택이나 회복이 필요합니다.')}if(s.hp>40)s.low=false;
 if(key==='salvage'){const surge=Math.floor(s.time/10)%3===2;if(s.mode<2){s.cargo+=(s.mode===1?4:2)*(1+s.level*.45)*dt;s.hp-=Math.max(.1,(s.mode===1?3.4:1)*(surge?1.7:1)-s.armor*.45)*dt;}else s.hp=Math.min(100,s.hp+4*dt);}
 if(key==='forge'){s.res+=([4,2.4,1][s.mode]+.8*s.level)*dt;s.hp=Math.min(100,s.hp+([-3,-.7,1.4][s.mode])*dt);}
 if(key==='route'&&!s.arrived){s.trip+=dt*(s.mode===1?1.75:1);if(s.mode===1)s.hp-=Math.max(.45,4.5-s.armor*.9)*dt;if(s.trip>=14){s.trip=14;s.arrived=true;s.delivered++;s.res+=s.mode===1?15:10;s.hp=Math.min(100,s.hp+4);notice('운송 도착! '+s.delivered+'/5. 다음 운송을 출발하세요.');}}
 check();update();}
function update(){if(!s)return;$('time').textContent=Math.max(0,Math.ceil(120-s.time))+'초';$('hp').textContent=Math.max(0,Math.ceil(s.hp))+'/100';$('resource').textContent=Math.floor(s.res);$('progress').textContent=s.delivered+'/'+(key==='salvage'?120:key==='forge'?6:5);$('pause').disabled=!['play','paused'].includes(s.status);$('pause').textContent=s.status==='paused'?'계속하기':'일시 정지';buttons.forEach((b,i)=>{b.disabled=s.status!=='play';if(!(key==='route'&&i===2))b.setAttribute('aria-pressed',String(i===s.mode))});upbuttons.forEach(b=>b.disabled=s.status!=='play');
 if(key==='salvage'){const surge=Math.floor(s.time/10)%3===2;$('banner').textContent=m.actions[s.mode][0]+' · 화물 '+Math.floor(s.cargo)+' · '+(surge?'높은 조수!':'다음 높은 조수 '+(20-Math.floor(s.time)%30+30)%30+'초');upbuttons[0].querySelector('small').textContent='수거 +45% · Lv.'+s.level+' · 비용 '+(18+6*s.level);upbuttons[1].querySelector('small').textContent='피해 -0.45/초 · Lv.'+s.armor+' · 비용 '+(15+5*s.armor);}
 if(key==='forge'){$('banner').textContent=m.actions[s.mode][0]+' · 생산 '+([4,2.4,1][s.mode]+s.level*.8).toFixed(1)+'/초 · 주문 '+s.delivered+'/6';upbuttons[0].querySelector('small').textContent='생산 +0.8/초 · Lv.'+s.level+' · 비용 '+(16+6*s.level);}
 if(key==='route'){$('banner').textContent=s.arrived?'도착 완료 · 다음 운송을 출발하세요':m.actions[s.mode][0]+' · 운송 '+Math.round(s.trip/14*100)+'%';upbuttons[0].querySelector('small').textContent='피해 -0.9/초 · Lv.'+s.armor+' · 비용 '+(12+4*s.armor);}
}
$('start').onclick=start;$('restart').onclick=()=>{if(s?.status==='play'||s?.status==='paused'){s.status='confirm';$('overlayTitle').textContent='처음부터 다시 시작';$('help').textContent='현재 판의 자원과 성장은 초기화됩니다. 다시 시작 버튼을 눌러 새 작전을 시작하세요.';$('start').textContent='다시 시작';$('overlay').hidden=false;update()}else start()};$('pause').onclick=()=>{if(!s)return;s.status=s.status==='paused'?'play':'paused';last=performance.now();notice(s.status==='paused'?'일시 정지됨':'작전 재개');update()};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'소리 끔':'소리 켬';$('sound').setAttribute('aria-pressed',String(!muted));tone()};document.addEventListener('visibilitychange',()=>{if(document.hidden&&s?.status==='play'){s.status='paused';notice('화면을 떠나 자동 일시 정지됐습니다.');update()}last=performance.now()});
const canvas=$('scene'),ctx=canvas.getContext('2d');let w=900,h=300;function resize(){const b=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);w=b.width;h=b.height;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(canvas);resize();
function draw(t){ctx.fillStyle='#0a2030';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1a394b';ctx.lineWidth=1;for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}const colors=['#62e3cc','#ffbd75','#aca7ff'];const col=colors[['salvage','forge','route'].indexOf(key)];const amount=s?.res||0,mode=s?.mode||0;ctx.font='12px system-ui';ctx.textAlign='center';
 if(key==='salvage'){for(let y=110;y<h;y+=35){ctx.strokeStyle='#245472';ctx.beginPath();for(let x=0;x<w;x+=10){const py=y+Math.sin(x*.022+t*.0015+y)*7;if(x===0)ctx.moveTo(x,py);else ctx.lineTo(x,py)}ctx.stroke()}const x=mode===2?w*.18:mode===0?w*.47:w*.77,y=h*.58;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(x-28,y);ctx.lineTo(x+28,y);ctx.lineTo(x+17,y+15);ctx.lineTo(x-18,y+15);ctx.fill();ctx.fillRect(x-7,y-18,14,18);for(let i=0;i<Math.min(10,Math.floor((s?.cargo||0)/5));i++){ctx.fillStyle='#ffce87';ctx.fillRect(x-25+i%5*11,y-28-Math.floor(i/5)*9,7,7)}ctx.fillStyle='#b6d6df';ctx.fillText('항구',w*.18,h-18);ctx.fillText('해변',w*.47,h-18);ctx.fillText('심해',w*.77,h-18);}
 if(key==='forge'){for(let i=0;i<3;i++){const x=w*(.22+i*.28),y=h*.57;ctx.save();ctx.translate(x,y);ctx.rotate(t*.0005*(s?.status==='play'?1:0)*(i+1));ctx.strokeStyle=colors[i];ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,35,0,Math.PI*2);ctx.stroke();for(let k=0;k<8;k++){ctx.rotate(Math.PI/4);ctx.fillStyle=colors[i];ctx.fillRect(28,-5,17,10)}ctx.restore();ctx.fillStyle='#bfd2dd';ctx.fillText(['채굴','제작','경비'][i],x,h-25)}for(let k=0;k<Math.min(12,Math.floor(amount/5));k++){ctx.fillStyle=col;ctx.fillRect(w*.45+k%6*15,h*.48-Math.floor(k/6)*16,10,10)}}
 if(key==='route'){ctx.strokeStyle='#396f6d';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(w*.12,h*.57);ctx.quadraticCurveTo(w*.5,h*.12,w*.88,h*.57);ctx.stroke();ctx.strokeStyle='#9c624c';ctx.beginPath();ctx.moveTo(w*.12,h*.57);ctx.lineTo(w*.88,h*.57);ctx.stroke();for(const x of [w*.12,w*.88]){ctx.fillStyle=col;ctx.beginPath();ctx.arc(x,h*.57,22,0,Math.PI*2);ctx.fill()}const f=(s?.trip||0)/14,x=w*.12+w*.76*f,y=mode===0?h*.57-Math.sin(f*Math.PI)*h*.22:h*.57;ctx.fillStyle='#f3d290';ctx.fillRect(x-12,y-10,24,20);ctx.fillStyle='#d5cfff';ctx.fillText('안전길',w*.5,h*.27);ctx.fillText('위험길',w*.5,h*.72)}
 if(s&&s.flash>0){ctx.strokeStyle=col;ctx.lineWidth=3;ctx.strokeRect(2,2,w-4,h-4)}ctx.fillStyle='#a6c3d3';ctx.textAlign='left';ctx.fillText('자동 '+(key==='route'?'운송':key==='forge'?'생산·방어':'수거')+' / 직접 선택',18,h-15);}
function loop(now){const dt=Math.min((now-last)/1000,.1);last=now;if(!document.hidden)tick(dt);draw(now);frame++;requestAnimationFrame(loop)}requestAnimationFrame(loop);buttons.forEach(b=>b.disabled=true);upbuttons.forEach(b=>b.disabled=true);
})();
